apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-gateway
  namespace: argocd
spec:
  project: default #every application belongs to a single project
  source:
    path: istio-gateway
    repoURL: https://github.com/jonacas93/argocd-examples.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-ingress
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true